const defaultFrontendUrl = process.env.FRONTEND_URL ?? 'http://127.0.0.1:5173';
const defaultBackendUrl = process.env.BACKEND_URL ?? 'http://127.0.0.1:3000';

const defaultSleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));

const assert = (condition, message) => {
  if (!condition) {
    throw new Error(message);
  }
};

const assertString = (value, message) => {
  assert(typeof value === 'string' && value.length > 0, message);
  return value;
};

export const waitForOk = async ({
  fetchImpl,
  label,
  retries = 30,
  sleep = defaultSleep,
  url,
}) => {
  for (let index = 0; index < retries; index += 1) {
    try {
      const response = await fetchImpl(url);
      if (response.ok) {
        return;
      }
    } catch {}

    await sleep(1000);
  }

  throw new Error(`No se pudo alcanzar ${label} en ${url}.`);
};

const readErrorBody = async (response) => {
  try {
    if (typeof response.text === 'function') {
      return await response.text();
    }

    if (typeof response.json === 'function') {
      return JSON.stringify(await response.json());
    }
  } catch {
    return '';
  }

  return '';
};

const requestJson = async ({
  body,
  fetchImpl,
  method = 'GET',
  path,
  token,
  backendUrl,
  headers = {},
}) => {
  const requestHeaders = {
    ...headers,
  };

  if (body !== undefined) {
    requestHeaders['Content-Type'] = 'application/json';
  }

  if (token) {
    requestHeaders.Authorization = `Bearer ${token}`;
  }

  const url = `${backendUrl}${path}`;
  const response = await fetchImpl(url, {
    method,
    headers: requestHeaders,
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  if (!response.ok) {
    const errorBody = await readErrorBody(response);
    const bodyDetails = errorBody ? ` Body: ${errorBody}` : '';
    throw new Error(`${method} ${url} fallo con status ${response.status}.${bodyDetails}`);
  }

  return response.json();
};

const login = async ({ backendUrl, email, fetchImpl, password }) => {
  const payload = await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: '/auth/login',
    body: {
      email,
      password,
    },
  });

  return {
    token: assertString(payload.accessToken, `El login de ${email} no devolvio accessToken.`),
    userId: assertString(payload.user?.id, `El login de ${email} no devolvio user.id.`),
  };
};

const makeDefaultScheduledAt = () => {
  const oneDayMs = 24 * 60 * 60 * 1000;
  const threeHoursMs = 3 * 60 * 60 * 1000;
  const conflictOffset = (Date.now() % 1000) * threeHoursMs;

  return new Date(Date.now() + 7 * oneDayMs + conflictOffset).toISOString();
};

export const runFullFlowSmoke = async ({
  backendUrl = defaultBackendUrl,
  fetchImpl = fetch,
  frontendUrl = defaultFrontendUrl,
  password = '123456',
  scheduledAt = makeDefaultScheduledAt(),
  sleep = defaultSleep,
  uniqueId = String(Date.now()),
  webhookSecret = process.env.MERCADOPAGO_WEBHOOK_SECRET,
} = {}) => {
  await waitForOk({ fetchImpl, label: 'backend', sleep, url: `${backendUrl}/health` });
  await waitForOk({ fetchImpl, label: 'frontend', sleep, url: `${frontendUrl}/login` });

  const client = await login({
    backendUrl,
    email: 'cliente@arreglaya.com',
    fetchImpl,
    password,
  });
  const professional = await login({
    backendUrl,
    email: 'pro@arreglaya.com',
    fetchImpl,
    password,
  });

  const categories = await requestJson({
    backendUrl,
    fetchImpl,
    path: '/categories',
  });

  assert(Array.isArray(categories) && categories.length > 0, 'No hay categorias disponibles.');
  const categoryId = assertString(categories[0]?.id, 'La primera categoria no tiene id.');

  const serviceRequest = await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: '/service-requests',
    token: client.token,
    body: {
      title: `QA full flow ${uniqueId}`,
      description: `Solicitud creada por smoke full flow ${uniqueId}.`,
      categoryId,
      city: 'Buenos Aires',
      zone: 'Palermo',
      budget: '18500',
      photos: [],
    },
  });
  const serviceRequestId = assertString(serviceRequest.id, 'La solicitud creada no devolvio id.');

  const quote = await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: `/service-requests/${serviceRequestId}/quotes`,
    token: professional.token,
    body: {
      serviceRequestId,
      amount: '18500',
      message: 'Smoke full flow quote generated by automated QA.',
    },
  });
  const quoteId = assertString(quote.id, 'La cotizacion creada no devolvio id.');
  const professionalId = assertString(
    quote.professionalId ?? professional.userId,
    'La cotizacion creada no devolvio professionalId.',
  );

  await requestJson({
    backendUrl,
    fetchImpl,
    method: 'PATCH',
    path: `/quotes/${quoteId}`,
    token: client.token,
    body: {
      status: 'accepted',
    },
  });

  const booking = await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: '/bookings',
    token: client.token,
    body: {
      serviceRequestId,
      professionalId,
      scheduledAt,
      notes: 'Smoke full flow booking.',
    },
  });
  const bookingId = assertString(booking.id, 'La reserva creada no devolvio id.');

  await requestJson({
    backendUrl,
    fetchImpl,
    method: 'PATCH',
    path: `/bookings/${bookingId}`,
    token: professional.token,
    body: {
      status: 'confirmed',
    },
  });

  const payment = await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: `/bookings/${bookingId}/payments`,
    token: client.token,
    body: {
      amountCents: 1850000,
      currency: 'ARS',
      description: 'Smoke full flow payment.',
    },
  });
  const paymentId = assertString(payment.id, 'El pago creado no devolvio id.');

  await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: '/payments/webhooks/mercadopago',
    headers: webhookSecret ? { 'x-webhook-secret': webhookSecret } : {},
    body: {
      externalReference: paymentId,
      status: 'approved',
    },
  });

  const receipt = await requestJson({
    backendUrl,
    fetchImpl,
    path: `/payments/${paymentId}/receipt`,
    token: client.token,
  });

  await requestJson({
    backendUrl,
    fetchImpl,
    method: 'PATCH',
    path: `/bookings/${bookingId}`,
    token: professional.token,
    body: {
      status: 'completed',
    },
  });

  const review = await requestJson({
    backendUrl,
    fetchImpl,
    method: 'POST',
    path: '/reviews',
    token: client.token,
    body: {
      bookingId,
      rating: 5,
      comment: 'Smoke full flow completed successfully.',
    },
  });

  return {
    frontend: `${frontendUrl}/login`,
    backend: `${backendUrl}/health`,
    login: 'ok',
    serviceRequestId,
    quoteId,
    bookingId,
    paymentId,
    receiptNumber: assertString(receipt.receiptNumber, 'El comprobante no devolvio numero.'),
    reviewId: assertString(review.id, 'La resena creada no devolvio id.'),
  };
};
